export interface ICompilerFull {
  id: string
  name: string
  deprecated: boolean
  style: string
}

export const compilersFull: ICompilerFull[] = [
  {
    id: 'fbc',
    name: 'Free Basic 1.04',
    deprecated: false,
    style: 'basic',
  },
  {
    id: 'gcc7_c11',
    name: 'GNU GCC 7.3 C11',
    deprecated: false,
    style: 'c',
  },
  {
    id: 'gcc_c17',
    name: 'GNU GCC 12.2 C17',
    deprecated: false,
    style: 'c',
  },
  {
    id: 'dotnet5_asp',
    name: 'C# (MS .NET 5.0 + ASP)',
    deprecated: true,
    style: 'csharp',
  },
  {
    id: 'dotnet6_asp',
    name: 'C# (MS .NET 6.0 + ASP)',
    deprecated: false,
    style: 'csharp',
  },
  {
    id: 'mono_csharp',
    name: 'Mono C# 5.2.0',
    deprecated: false,
    style: 'csharp',
  },
  {
    id: 'clang14_cpp20',
    name: 'Clang 16.0.0 C++20',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'gcc7.3-thread',
    name: 'gcc7.3-thread',
    deprecated: true,
    style: 'c_cpp',
  },
  {
    id: 'gcc7_3',
    name: 'GNU c++17 7.3',
    deprecated: false,
    style: '',
  },
  {
    id: 'gcc7_o0',
    name: 'GNU C++17 7.3 (-O0)',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'gcc_cpp20',
    name: 'GNU GCC 12.2 C++20',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'gcc_docker',
    name: 'GCC 5.4.0 C++14',
    deprecated: true,
    style: 'c_cpp',
  },
  {
    id: 'dmd',
    name: 'dmd',
    deprecated: false,
    style: 'd',
  },
  {
    id: 'gdc',
    name: 'GDC 4.9',
    deprecated: true,
    style: 'd',
  },
  {
    id: 'dart_2_14',
    name: 'Dart 2.19.2',
    deprecated: false,
    style: 'dart',
  },
  {
    id: 'golang_docker',
    name: 'Golang 1.21.0',
    deprecated: false,
    style: 'golang',
  },
  {
    id: 'golang_docker_make',
    name: '(make) Golang 1.21.0',
    deprecated: false,
    style: 'golang',
  },
  {
    id: 'haskell',
    name: 'Haskell 7.10.2',
    deprecated: false,
    style: 'haskell',
  },
  {
    id: 'java8',
    name: 'Oracle Java 8',
    deprecated: true,
    style: 'java',
  },
  {
    id: 'javac',
    name: 'Oracle Java 8 (48ML)',
    deprecated: true,
    style: 'java',
  },
  {
    id: 'jdk17',
    name: 'Java 17 (Temurin JDK)',
    deprecated: false,
    style: 'java',
  },
  {
    id: 'jdk19',
    name: 'Java 19 (Temurin JDK)',
    deprecated: true,
    style: 'java',
  },
  {
    id: 'jdk20',
    name: 'Java 20 (Temurin JDK)',
    deprecated: false,
    style: 'java',
  },
  {
    id: 'openjdk11_x64',
    name: 'OpenJDK Java 11',
    deprecated: true,
    style: 'java',
  },
  {
    id: 'node12_mocha',
    name: 'Mocha (Node.js 12)',
    deprecated: true,
    style: 'javascript',
  },
  {
    id: 'nodejs_16',
    name: 'Node.js 16.17.0',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'nodejs_18',
    name: 'Node.js 18.7.0',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'nodejs_jest',
    name: 'nodejs_jest',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'nodejs_new',
    name: 'Node.js 14.15.5',
    deprecated: true,
    style: 'javascript',
  },
  {
    id: 'kotlin_1_5_0',
    name: 'Kotlin 1.5.32 (JRE 11)',
    deprecated: true,
    style: 'kotlin',
  },
  {
    id: 'kotlin_1_8_0',
    name: 'Kotlin 1.8.0 (JRE 11)',
    deprecated: false,
    style: 'kotlin',
  },
  {
    id: 'kumir',
    name: 'kumir 2.1.0-rc9',
    deprecated: false,
    style: 'nohighlight',
  },
  {
    id: 'lua_5_4',
    name: 'Lua 5.4',
    deprecated: false,
    style: 'lua',
  },
  {
    id: 'cpp20-make-clang14',
    name: '(Make) Clang 16.0.0 C++20',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'dotnet5',
    name: '(Make) C# (MS .Net Core 5.0)',
    deprecated: true,
    style: 'csharp',
  },
  {
    id: 'dotnet6',
    name: '(Make) C# (MS .Net Core 6.0)',
    deprecated: false,
    style: 'csharp',
  },
  {
    id: 'gcc_c17_make',
    name: '(make) GNU GCC 12.2 C17',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'gcc_cpp20_make',
    name: '(make) GNU GCC 12.2 C++20',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'gcc_docker2_make',
    name: '(make) GCC  C++17',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'go-lyceum',
    name: '(make) Lyceum Go',
    deprecated: false,
    style: 'golang',
  },
  {
    id: 'idao2022',
    name: '(make) idao2022',
    deprecated: false,
    style: '',
  },
  {
    id: 'idao2022_final',
    name: '(make) idao2022 final',
    deprecated: false,
    style: '',
  },
  {
    id: 'ipython3',
    name: '(make) ipython3',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'ipython3v2',
    name: '(make) ipython3v2',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'jdk17_make',
    name: '(make) Java 17 (Temurin JDK)',
    deprecated: false,
    style: 'java',
  },
  {
    id: 'js-blitz',
    name: '(make) js-blitz',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'lyceum_go_test',
    name: '(make) Lyceum Go Test',
    deprecated: false,
    style: 'golang',
  },
  {
    id: 'lyceum_python_test',
    name: '(make) Lyceum Python Test',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'make',
    name: 'Make',
    deprecated: true,
    style: 'nohighlight',
  },
  {
    id: 'make2',
    name: 'make2',
    deprecated: true,
    style: 'nohighlight',
  },
  {
    id: 'mlblitz_python27_numpy',
    name: '(make) python2.7+numpy',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'nodejs_16_make',
    name: '(make) Node.js 16.17.0',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'nodejs_18_make',
    name: '(make) Node.js 18.16.0',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'postgres',
    name: '(make) postgres',
    deprecated: false,
    style: 'pgsql',
  },
  {
    id: 'python-handbook',
    name: '(make) python-handbook',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'python-lyceum',
    name: '(make) python-lyceum',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'python3_7',
    name: '(make) Python 3.7.3+modules',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'python3_docker_make',
    name: '(make) Python 3.11.4',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'python_docker_make',
    name: '(make) python_docker_make',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'swift-5_3_make',
    name: '(make) Swift 5.7.3',
    deprecated: false,
    style: 'swift',
  },
  {
    id: 'tex',
    name: '(make) tex',
    deprecated: false,
    style: 'nohighlight',
  },
  {
    id: 'tmp_py',
    name: '(make) tmp_py',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'ocaml4',
    name: 'ocaml 4.02.3',
    deprecated: false,
    style: 'ocaml',
  },
  {
    id: 'dcc',
    name: 'Delphi (FPC 3.2.0)',
    deprecated: false,
    style: 'delphi',
  },
  {
    id: 'fpc30',
    name: 'Free Pascal 3.2.0',
    deprecated: false,
    style: 'pascal',
  },
  {
    id: 'pascal_abc',
    name: 'PascalABC.NET 3.8.3',
    deprecated: false,
    style: 'pascal',
  },
  {
    id: 'perl',
    name: 'Perl 5.14',
    deprecated: false,
    style: 'perl',
  },
  {
    id: 'php7_3_5',
    name: 'PHP 7.3.5',
    deprecated: true,
    style: 'php',
  },
  {
    id: 'php8_1',
    name: 'PHP 8.1',
    deprecated: false,
    style: 'php',
  },
  {
    id: 'pypy3_7_1_0',
    name: 'Python 3.9 (PyPy 7.3.11)',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'python2_6',
    name: 'Python 2.7',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'python3_7_3',
    name: 'Python 3.7.3',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'python3_docker',
    name: 'Python 3.11.4',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'r_core',
    name: 'R 2.14.1',
    deprecated: true,
    style: 'r',
  },
  {
    id: 'r_modules',
    name: 'R 3.6.3 + Modules',
    deprecated: false,
    style: 'r',
  },
  {
    id: 'ruby2',
    name: 'Ruby 2.2.3',
    deprecated: false,
    style: 'ruby',
  },
  {
    id: 'rust154',
    name: 'Rust 1.71.1',
    deprecated: false,
    style: 'rust',
  },
  {
    id: 'scala_docker',
    name: 'Scala 2.13.4',
    deprecated: false,
    style: 'scala',
  },
  {
    id: 'bash',
    name: 'GNU bash 4.2.24',
    deprecated: false,
    style: '',
  },
  {
    id: 'data-analysis-handbook',
    name: 'Python 3.8 (Handbook DS)',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'java17_json',
    name: 'OpenJDK 17 + json',
    deprecated: false,
    style: 'java',
  },
  {
    id: 'mlblitz',
    name: 'python3.6+numpy+pandas',
    deprecated: true,
    style: 'python',
  },
  {
    id: 'mlblitz_python26_numpy',
    name: '(make) yandexdataschool',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'mono_csharp_5',
    name: '(special) Mono C# 5',
    deprecated: true,
    style: 'csharp',
  },
  {
    id: 'python3-ml',
    name: '(make) python3-ml',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'python3_7_ml_modules',
    name: 'Python 3.7.3 ML',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'r-ml',
    name: '(make) r-ml',
    deprecated: false,
    style: 'r',
  },
  {
    id: 'screenshots-checker',
    name: 'screenshots-checker',
    deprecated: false,
    style: 'javascript',
  },
  {
    id: 'shagraev',
    name: 'Python 3.7 + network + requests',
    deprecated: false,
    style: 'python',
  },
  {
    id: 'shagraev_cpp',
    name: 'GNU c++ 11 + net + curl + json',
    deprecated: false,
    style: 'c_cpp',
  },
  {
    id: 'shagraev_go',
    name: 'Golang 1.14.4 + network',
    deprecated: false,
    style: 'golang',
  },
  {
    id: 'shagraev_java',
    name: 'Java 8 + network + json-simple',
    deprecated: false,
    style: 'java',
  },
  {
    id: 'tmp_gcc_coursera',
    name: 'g++17 7.3 controlled',
    deprecated: true,
    style: 'c_cpp',
  },
  {
    id: 'ysda-ml',
    name: '(make) ysda-ml',
    deprecated: false,
    style: '',
  },
  {
    id: 'sqlite3',
    name: 'SQLite 3.31.1',
    deprecated: false,
    style: '',
  },
  {
    id: 'swift-5_1',
    name: 'Swift 5.8.1',
    deprecated: false,
    style: 'swift',
  },
]
